### PR TITLE
Adding Portuguese translation

### LINKED ISSUE #8: Add Portuguese translation
It would be nice to have a Portuguese translation of the library. :portugal: 

The _Translation Editor_ in [_Android Studio_](https://developer.android.com/studio/) let's you easily identify the missing translations as shown in the screenshot.

Android Studio Translation Editor

# TODOs

- [x] Add new translations in `roadsigns/src/main/res/values-pt/strings.xml`
  - Adding a new language can be done via the _Translation Editor_: the earth icon at top left.
  - Alternatively, you can just copy the English file from `values/strings.xml` to `values-pt/strings.xml` and edit the strings manually.
  - Do not modify, commit files outside of the `-pt` folder.
  - Do not translate strings located in the `app` module.
  - Do not translate strings marked as `translatable="false"`.
  - Please do not commit to the `master` branch. Create a new branch like `portuguese-translation` for the pull request.
  - Check that your translation string is not wrapped in double quotes (`"`) or includes unneeded whitespace.

# Related
- [Localize the UI with Translations Editor](https://developer.android.com/studio/write/translations-editor.html)

---

:left_speech_bubble: If you want to work on this issue please leave a "I like to work on this" comment here.

### PR DESCRIPTION
**Pull request by tdopires**
Fixes #8 

Adding Portuguese 🇵🇹  translation on the library, as defined on [issue#8](https://github.com/Umweltzone/roadsigns/issues/8)

Here's some evidence on the demo app...

### CODE REVIEW

**Comment by tdopires** [comment]
@johnjohndoe , I think it would be nice to place the full text of the selected option somewhere else on the screen, since the labels are quite long for the `Spinner` when the device is in portrait... 🤔 
What do you think?

**Comment by tdopires** [comment]
Fixes #8

**Review by johnjohndoe — APPROVED** [review]
Muito obrigado @tdopires for translating the strings to Portuguese!

I checked your work and found no mistakes. That means: time to merge :guitar:

**Comment by johnjohndoe** [comment]
@tdopires Regarding the `Spinner`, I agree, it is not optimal. I tried quickly to make it a multiline spinner but could not do this just via XML. I guess one would need to create a custom view. If you feel like you are welcome to try it out.

**Comment by tdopires** [comment]
Yes, I think a custom view is required for this... I'll try later and let you know of the results!

**Pull request merged**
